### ISSUE TITLE
Feature request: Support yaml format for configuration files

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/client-dotnet#141]
We support `ReportPortal.json` file:
```json
{
  "server": {
    "url": "https://demo.reportportal.io/api/v1",
    "project": "default_project",
    "authentication": {
      "uuid": "aa19555c-c9ce-42eb-bb11-87757225d535"
    }
}
```

It would be good to support `ReportPortal.yaml` file as well:
```yaml
server:
  url: https://demo.reportportal.io/api/v1
  project: default_project
  authentication:
    uuid: aa19555c-c9ce-42eb-bb11-87757225d535
```
